[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "php artisan config:cache && php artisan route:cache && php artisan view:cache && /start-container.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.preDeployCommand]
command = "php artisan migrate --force && php artisan db:seed --force"
